---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.6.0

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: opscode-ubuntu-12.04
      box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    driver_config:
      box: opscode-ubuntu-14.04
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
    run_list:
      - recipe[apt]

suites:
  - name: default
    data_bags_path: "test/integration/mysql/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/mysql/data_bag_key"
    run_list:
      - recipe[iptables]
      - recipe[openssh::iptables]
      - recipe[redmine2]
      - recipe[redmine2::iptables]
    attributes:
      redmine:
        host: redmine.dev
        db:
          type: sqlite
        ssl_data_bag_name: redmine_example_com
  - name: mysql
    data_bags_path: "test/integration/mysql/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/mysql/data_bag_key"
    run_list:
      - recipe[iptables]
      - recipe[openssh::iptables]
      - recipe[redmine2]
      - recipe[redmine2::iptables]
    attributes:
      redmine:
        host: redmine.dev
        db:
          type: mysql
        ssl_data_bag_name: redmine_example_com
      mysql:
        server_root_password: q654321
        server_repl_password: q654321
        server_debian_password: q654321
  - name: postgresql
    run_list:
      - recipe[iptables]
      - recipe[openssh::iptables]
      - recipe[postgresql::server]
      - recipe[redmine2]
      - recipe[redmine2::iptables]
    attributes:
      redmine:
        host: redmine.dev
        db:
          type: postgresql
      postgresql:
        password:
          postgres: q654321
      build_essential:
        compiletime: true
